# Generated by Django 4.1.7 on 2023-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_usercategory_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
