# Generated by Django 4.1.7 on 2023-03-16 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_customuser_category_remove_customuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
    ]
