# Generated by Django 4.1.7 on 2023-03-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagePath',
            field=models.CharField(default='images/categories/1.png', max_length=100),
        ),
    ]
