# Generated by Django 4.1.7 on 2023-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_category_imagepath_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imagePath',
            field=models.CharField(blank=True, default='images/categories/1.png', max_length=100),
        ),
    ]
