# Generated by Django 4.1.7 on 2023-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.ManyToManyField(default=0, through='main_app.UserCategory', to='main_app.category'),
        ),
    ]
