# Generated by Django 4.1.7 on 2023-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
