# Generated by Django 4.1.7 on 2023-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_usercategory_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
