# Generated by Django 4.1.7 on 2023-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exercise_user_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='im', upload_to='images/profile_images'),
        ),
    ]
